# Generated by Django 5.0 on 2025-07-14 13:02

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('SBI', 'SBI'), ('HDFC', 'HDFC'), ('ICICI', 'ICICI'), ('AXIS', 'AXIS'), ('KOTAK', 'KOTAK'), ('BOB', 'BOB'), ('IDFC', 'IDFC'), ('YES', 'YES'), ('RBL', 'RBL'), ('AMEX', 'AMEX'), ('PNB', 'PNB'), ('AU', 'AU'), ('ONECARD', 'ONECARD'), ('DBS', 'DBS'), ('INDUSIND', 'INDUSIND'), ('UNION', 'UNION'), ('FEDERAL', 'FEDERAL'), ('HSBC', 'HSBC'), ('CANARA', 'CANARA'), ('BOI', 'BOI'), ('INDIAN', 'INDIAN'), ('OTHER', 'OTHER')], max_length=16)),
                ('card_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('expiry', encrypted_model_fields.fields.EncryptedCharField()),
                ('cvv', encrypted_model_fields.fields.EncryptedCharField()),
                ('card_variant', models.CharField(blank=True, max_length=50, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
